### ISSUE TITLE
关于格局

### ISSUE THREAD

**Issue by 63isOK** [63isOK/love#3]
此时此刻看到三年前遇到的困难 还和当初一样难受吗

任何谜题都是基于当前资源设计的 只要跳出这个圈子 就会看到无数种可能的解法 因为环境决定了资源 基于资源设计了谜题 当有更高的格局或更强的资源介入 谜题就像是一加一

所以提升人生的格局是非常重要的 也是必须的 不然每天都是为负能量而生气 就看不到快乐了 身而为人 快乐很重要 或者说是最重要的

**Comment by 63isOK** [comment]
不管是易经的屯卦蒙卦 或是之前记录的认知墙/认知边界 还是现在谈到的基于资源设计的谜题 都是说的同一个事 可以说看问题的高度或格局

**Comment by 63isOK** [comment]
协作的过程中会产生两种问题

- 认知不一致
- 格局不够

前者通过沟通可以解决 后者需要引入新的知识

**Comment by 63isOK** [comment]
当下担子 静下心 拼一品大师的杰作 格局又大了一点

这里的杰作主要指有前沿思想的书籍 看一下也觉得值回票价

**Comment by 63isOK** [comment]
士别三日刮目相看 说明人的潜力是无穷的 只是分橘生淮南和淮北 作为运营者 想要持续获得成功 单靠技术或资金 是远远不够的 考剩余价值也不够 还是靠人格魅力

**Comment by 63isOK** [comment]
有什么技术是比别人领先五年而不会被超越的 资金到什么程度才算雄厚 比倒下的世界500强还多吗

靠技术和人才 可以打赢几场 想要一直赢 运营者的人格魅力是第一要务

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的.

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的å

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的å

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的å

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的å

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的å

**Comment by zwf193071** [comment]
福报是什么 有书说福报是跟对老板 或许老板要求员工996 给公司带来了新气象 有了利润 员工的目标也实现了 这应该是一个双赢的现象 

或许对于某些有人格魅力的老板来说 说一句996是福报 是正确的å
